#!/bin/sh

set -e

case "$1" in
  configure)
    :
    #remove varnish startup
    service varnish stop
    update-rc.d -f varnish remove
    
    #add opencpu-cache startup script
	chmod 755 /etc/init.d/opencpu-cache
	update-rc.d opencpu-cache defaults
	
	#start the service
	service opencpu-cache start
    ;;
  abort-upgrade | abort-remove | abort-deconfigure)
    :
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

#DEBHELPER#

exit 0

