#!/bin/sh
### BEGIN INIT INFO
# Provides:          opencpu_server
# Required-Start:    $local_fs $remote_fs $network $syslog $named apache2 apparmor
# Required-Stop:     $local_fs $remote_fs $network $syslog $named apache2 apparmor
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop OpenCPU server.
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    /usr/lib/opencpu/scripts/killorphans.sh &
	/usr/lib/opencpu/scripts/sites.sh
	/usr/lib/opencpu/scripts/apps.sh
	a2ensite opencpu
	a2ensite opencpu-apps
	service apache2 restart
	echo "opencpu enabled"
    ;;
  stop)
    kill $(pgrep killorphans.sh)
	a2dissite opencpu
	a2dissite opencpu-apps
	service apache2 restart
	echo "opencpu disabled"
    ;;
  restart | force-reload)
	$0 stop
	$0 start    
	;;
  *)
    echo "Usage: sudo service opencpu-server {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
